name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.7'

    - name: Install dependencies
      run: make install

    - name: Check type hints
      run: make build

    - name: Run tests
      run: make test
